In [4]:
import torch
X = torch.Tensor(2,3)
X

tensor([[0.0000e+00, 0.0000e+00, 3.4332e-06],
        [2.6589e+23, 2.7002e-06, 5.2900e-08]])

In [7]:
X = torch.tensor([[1,2,3],[4,5,6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

torch.tensor : data, dtype, device, requires_grad ...

In [9]:
X_tensor = torch.tensor(data=[2.0,3.0], requires_grad=True)

In [40]:
x = torch.tensor(data=[2.0,3.0], requires_grad=True)
y=x**2
z=2*y+3

target = torch.tensor([3.0,4.0])
loss = torch.sum(torch.abs(z-target))
loss.backward()

print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


In [16]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

torch.nn :: 신경망 모델  
torch.optim :: 경사하강법 알고리즘  
torch.nn.init :: 텐서에 초기값을 주는 함수

In [45]:
num_data = 1000
num_epoch = 500

x = init.uniform_(torch.Tensor(num_data,1), -10,10)
noise = init.normal_(torch.FloatTensor(num_data,1), std=1)
y=2*x+3
y_noise = 2*(x+noise)+3

torch.Tensor(1000,1) : 1000x1짜리 벡터를 생성하고 그 값을 랜덤하게 채워넣어라  
init.uniform_(A , -10,10) : A값을 -10~10 사이의 유니폼분포에서 샘플링해서 채워라  

In [63]:
model = nn.Linear(1,1)
loss_func = nn.L1Loss()

nn.Linear(a,b) : a = 데이터의 변수 갯수, b = 출력할 결과의 변수갯수  

In [64]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

optim.SGD : 최적화 알고리즘 중 Stochastic Gradient Descent 방법을 선택  
optim.SGD(model.parameters(), lr=0.01) : 앞에서 정의한 model object에서 설정한 파라미터들을 최적화할 파라미터로 사용, Learning Rate=0.01로 설정

In [72]:
label = y_noise
for i in range(num_epoch) :
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output, label)
    loss.backward()
    optimizer.step()
    
    if i %10==0:
        print(loss.data)
        
    param_list=list(model.parameters())
    print(param_list[0].item(), param_list[1].item())

tensor(1.6523)
2.003976821899414 2.5744683742523193
2.0037872791290283 2.5757484436035156
2.003784656524658 2.5770485401153564
2.0035951137542725 2.5783286094665527
2.0034055709838867 2.579608678817749
2.0034029483795166 2.58090877532959
2.003213405609131 2.582188844680786
2.003023862838745 2.5834689140319824
2.0028343200683594 2.5847489833831787
2.0028316974639893 2.5860490798950195
tensor(1.6507)
2.0026421546936035 2.587329149246216
2.0024526119232178 2.588609218597412
2.0024499893188477 2.589909315109253
2.002260446548462 2.591189384460449
2.002070903778076 2.5924694538116455
2.0018813610076904 2.593749523162842
2.0018787384033203 2.5950496196746826
2.0016891956329346 2.596329689025879
2.001499652862549 2.597609758377075
2.001310110092163 2.5988898277282715
tensor(1.6490)
2.0013909339904785 2.6001698970794678
2.0012848377227783 2.6014299392700195
2.001178741455078 2.6026899814605713
2.001072645187378 2.603950023651123
2.001189708709717 2.6051700115203857
2.0013067722320557 2.6063899

1.998957872390747 2.7724058628082275
1.9989047050476074 2.7730257511138916
1.9988515377044678 2.7736456394195557
1.9987983703613281 2.7742655277252197
1.9987452030181885 2.774885416030884
1.9986920356750488 2.775505304336548
1.9986388683319092 2.776125192642212
1.9985857009887695 2.776745080947876
1.9985325336456299 2.77736496925354
tensor(1.6322)
1.9984793663024902 2.777984857559204
1.9983333349227905 2.7785849571228027
1.9981873035430908 2.7791850566864014
1.9983253479003906 2.77978515625
1.9983705282211304 2.780365228652954
1.9984157085418701 2.780945301055908
1.9984608888626099 2.7815253734588623
1.9985060691833496 2.7821054458618164
1.9985512495040894 2.7826855182647705
1.998596429824829 2.7832655906677246
tensor(1.6319)
1.9986416101455688 2.7838456630706787
1.9986867904663086 2.784425735473633
1.9987319707870483 2.785005807876587
1.998777151107788 2.785585880279541
1.9988223314285278 2.786165952682495
1.9987348318099976 2.7867259979248047
1.9986473321914673 2.7872860431671143
1.9

1.9951452016830444 2.863607406616211
1.995163917541504 2.863847494125366
1.9953639507293701 2.864067554473877
1.9953826665878296 2.8643076419830322
1.995401382446289 2.8645477294921875
1.9954200983047485 2.8647878170013428
1.995438814163208 2.865027904510498
1.9954575300216675 2.8652679920196533
tensor(1.6282)
1.995476245880127 2.8655080795288086
1.9954949617385864 2.865748167037964
1.995513677597046 2.865988254547119
1.9955323934555054 2.8662283420562744
1.9955511093139648 2.8664684295654297
1.9955698251724243 2.866708517074585
1.9955885410308838 2.8669486045837402
1.9956072568893433 2.8671886920928955
1.9956259727478027 2.867428779602051
1.9956446886062622 2.867668867111206
tensor(1.6281)
1.9956634044647217 2.8679089546203613
1.9956821203231812 2.8681490421295166
1.9957008361816406 2.868389129638672
1.9957195520401 2.868629217147827
1.9957382678985596 2.8688693046569824
1.995756983757019 2.8691093921661377
1.9957756996154785 2.869349479675293
1.995794415473938 2.8695895671844482
1.99

optimizer.zero_grad() : 에포크가 새로 시작할 때 마다 그레디언트를 0으로 초기화  
output = model(x) : 앞에서 정의한 선형모형인 model 오브젝트에 데이터인 x를 전달, 즉 선형식의 결과를 output에 전달
loss를 L1-loss로 설정 후 backward() 를 통해 선형식의 파라미터인 w,b를 업데이트 (역전파 방법)  
optimizer.step() : 앞에서 정의한 optimizer함수에 인자로 들어가는 model.parameters() 들에 lr을 곱한 뒤 빼서 w,b를 업데이트  


In [74]:
loss.data

tensor(1.6278)